apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-mjac
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-mjac
    app.kubernetes.io/part-of: test-app-fhpu
  name: test-component-mjac
  namespace: pipeline-e2e-yjjn
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-mjac
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-mjac
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images@sha256:a1c96ff5c278e6eae51f823daef0477600e88567eafcf3222a50169bfbebc156
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
