apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-mjac
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-mjac
    app.kubernetes.io/part-of: test-app-fhpu
  name: test-component-mjac
  namespace: pipeline-e2e-yjjn
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: test-component-mjac
    weight: 100
status: {}
